# .github/workflows/telegram_message.yml
name: telegram_message

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]
  repository_dispatch:
    types: [discussion_reaction]    

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    env:
      TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Build message
        run: |
          set -euo pipefail

          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"
          RUN_URL="https://github.com/${REPO}/actions/runs/${{ github.run_id }}"
          EVENT_NAME="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"

          # Pull fields from the raw webhook; missing keys become empty strings.
          DISC_NUM="$(jq -r '.discussion.number // ""' "$GITHUB_EVENT_PATH")"
          DISC_TITLE="$(jq -r '.discussion.title // ""' "$GITHUB_EVENT_PATH")"
          DISC_URL="$(jq -r '.discussion.html_url // ""' "$GITHUB_EVENT_PATH")"
          CATEGORY="$(jq -r '.discussion.category.name // ""' "$GITHUB_EVENT_PATH")"

          COMMENTER="$(jq -r '.comment.user.login // ""' "$GITHUB_EVENT_PATH")"
          COMMENT_URL="$(jq -r '.comment.html_url // ""' "$GITHUB_EVENT_PATH")"
          COMMENT_BODY="$(jq -r '.comment.body // ""' "$GITHUB_EVENT_PATH")"

          # Soft truncate comment to keep under Telegram’s 4096 char limit.
          MAX=1200
          if [ "${#COMMENT_BODY}" -gt "$MAX" ]; then
            COMMENT_BODY="${COMMENT_BODY:0:$MAX}…[truncated]"
          fi

          TEXT="
          Event: ${EVENT_NAME} / ${ACTION}
          Discussion #${DISC_NUM}: ${DISC_TITLE}
          Category: ${CATEGORY}
          Discussion URL: ${DISC_URL}
          
          Commenter: ${COMMENTER}
          Comment URL: ${COMMENT_URL}
          Comment:
          ${COMMENT_BODY}
          
          Repository: ${REPO}
          Trigger actor: ${ACTOR}
          Run: ${RUN_URL}
          "

          printf "%s" "${TEXT}" > message.txt
          echo "--- message.txt preview ---"
          sed -n '1,120p' message.txt

      - name: Send Telegram message
        run: |
          set -euo pipefail
          curl -fsSL \
            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d "chat_id=${TG_CHAT_ID}" \
            --data-urlencode "text=$(cat message.txt)" \
            -d "disable_web_page_preview=true"
